version: '3'
services:
  test:
    build: .
    environment:
      MIX_ENV: dev
      ERL_AFLAGS: -kernel shell_history enabled  shell_history_path '"/var/cache"'
      DEBUG: ${DEBUG-}
      YEAR: ${YEAR:-2020}
    volumes:
      - ./.cache:/var/cache
      - .:/app:ro
      - ../data:/data:ro
    command: mix test ${OPTS-}
