version: '3'
services:
  test:
    build: .
    environment:
      PYTHONPATH: ./src
      PYTHONDONTWRITEBYTECODE: 1
    volumes:
      - .:/app:ro
      - ./prof:/app/prof
      - ../data:/data:ro
    command: pytest -p no:cacheprovider ${OPTS}
