version: '3'
services:
  test:
    build: .
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      YEAR: ${YEAR}
    volumes:
      - .:/app:ro
      - ./prof:/app/prof
      - ../data:/data:ro
      - './build/profile/:/root/.ipython/profile_default/'
    command: pytest -p no:cacheprovider ${OPTS}
