version: '3'

volumes:
  gradle-cache:

services:
  test:
    image: gradle:jdk17-alpine
    working_dir: /home/gradle/aoc
    volumes:
      - .:/home/gradle/aoc
      - ../data:/data:ro
      - gradle-cache:/home/gradle/.gradle
    command: gradle test ${OPTS}