version: '3'

volumes:
  ? m2-cache

services:
  test:
    image: clojure:temurin-17-lein-alpine
    working_dir: /app
    volumes:
      - .:/app
      - ../data:/data:ro
      - m2-cache:/root/.m2
    command: lein eftest ${OPTS}
